appName: SCORES-MANAGER-UI-FLASK
appShortName: SMGR
logLevel: WARN
authors:
  - Andrey Potapov
  - Sergei Boikov  

paths:
  workingpath: 'D:\GIT\MSBI.LAB\_RNT\ScoresManager.WebUI'
  excluded_paths: ''

flags:
  debugmode: False

databases:
  postgres:
    host: ENVOS_SMGR_VALUE_02
    port: 6432
    sslmode: verify-full
    dbname: ENVOS_SMGR_VALUE_03
    user: mentor
    username: mentor
    target_session_attrs: read-write    
    password: ENVOS_SMGR_VALUE_01
    working_schema: lab
    api_schema: mentor
    